### ISSUE TITLE
lutris not required?

### ISSUE THREAD

**Issue by fedario** [GloriousEggroll/flatpak-leagueoflegends#1]
Hi there,
first of all: thank you for this awesome flatpak! ❤️ 

After struggling with the dependencies required to install lutris, I tried installing your package without it and it worked. It seems like lutris isn't really a dependency, is that correct?
If so, I think it would be helpful to mention that it is optional in the readme.

**Comment by GloriousEggroll** [comment]
You are correct. I forgot to change the readme. The flatpak compiles wine and the necessary dependencies from source. I will edit the readme and close this ticket
