### ISSUE TITLE
League of Legends completely resets after it stops running. 

### ISSUE THREAD

**Issue by Saroufim** [GloriousEggroll/flatpak-leagueoflegends#3]
There's launcher update and a 20~ GB patch to download. Once you quit the application, the download progress resets and the launcher rolls back to its initial version. This happens every time.

**Comment by GloriousEggroll** [comment]
never had this issue before, but anyway I just updated the necessary overrides. please test.

**Comment by Saroufim** [comment]
That seemed to have worked. Thanks!
