### ISSUE TITLE
Launcher authentication problems

### ISSUE THREAD

**Issue by DrunkCat159** [GloriousEggroll/flatpak-leagueoflegends#4]
It is rarly possibile to login in. I can login with the same client on VM WARE with guest Windows Xp Sp3.
I am starting the client with this commnad: flatpak run org.RiotGames.leagueoflegends

**Comment by GloriousEggroll** [comment]
Over the weekend I made a fresh install on two computers at two different places using a freshly compiled flatpak. I had no problems logging in on either of them, and have not had any other reports of login problems.

Closing this unless it's confirmed by multiple sources with valid logs.

**Comment by DrunkCat159** [comment]
Ok I have removed everything and carefully followed the install instructions again, the problem still persist!
