### ISSUE TITLE
error: Build directory ../leagueoflegends not initialized, use flatpak build-init

### ISSUE THREAD

**Issue by LeandroStanger** [GloriousEggroll/flatpak-leagueoflegends#7]
org.freedesktop.Platform/i386/1.6 already installed, skipping
org.freedesktop.Sdk/i386/1.6 already installed, skipping
error: Build directory leagueoflegends already initialized
./flatpak-make: line 159: curl: command not found
./flatpak-make: line 160: curl: command not found
./flatpak-make: line 161: curl: command not found
./flatpak-make: line 162: curl: command not found
./flatpak-make: line 163: curl: command not found
cat: *.tar.gz: No such file or directory

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
./flatpak-make: line 167: cd: openldap-2.4.42+dfsg: No such file or directory
error: Build directory ../leagueoflegends not initialized, use flatpak build-init
error: Build directory ../leagueoflegends not initialized, use flatpak build-init
error: Build directory ../leagueoflegends not initialized, use flatpak build-init
./flatpak-make: line 173: cd: wine-wine-3.4: No such file or directory
./flatpak-make: line 175: ../wine-staging-3.4/patches/patchinstall.sh: No such file or directory
applying 00*.patch
patch: **** Can't open patch file '../wine-pba-heap_size_envvars-v3.4/patches/00*.patch' : No such file or directory
oh nooooo.. 00*.patch broke somehow
./flatpak-make: line 185: autoreconf: command not found
error: Build directory ../leagueoflegends not initialized, use flatpak build-init
error: Build directory ../leagueoflegends not initialized, use flatpak build-init
error: Build directory ../leagueoflegends not initialized, use flatpak build-init
rm: cannot remove ‘leagueoflegends/files/share/applications/wine.desktop’: No such file or directory
+ chmod +x leagueoflegends/files/bin/run.sh
chmod: cannot access ‘leagueoflegends/files/bin/run.sh’: No such file or directory

**Comment by GloriousEggroll** [comment]
./flatpak-make: line 163: curl: command not found

you need to install curl on your system

**Comment by LeandroStanger** [comment]
@ramcq How to install curl?
